### ISSUE TITLE
Realtime info

### ISSUE THREAD

**Issue by joao-vasconcelos** [carrismetropolitana/website#1]
Coisas para fazer:

**Lançamento (21 de Setembro)**
- [x] Não mostrar paragens finais
- [x] Feedback sobre o tempo real (precisão da estimativa)

**Upgrade 1 (28 de Setembro)**
- [x] Progressive Web App (PWA)
- [ ] Correção de atualização de GPS
- [ ] Melhorias de Acessibilidade

**Upgrade 2 (5 de Outubro)**
- [ ] Avisos e Alertas
- [ ] Não mostrar mais do que 3 viagens no passado
- [ ] Destacar paragens da viagem selecionada (keep selected trip in state)
- [ ] Animação do veículo
- [ ] Arranjar zoom automático do mapa
- [ ] Opacidade veículo em caso de delay elevado

**Upgrade 3 (12 de Outubro)**
- [ ] Paragens favoritas
- [ ] Horários de outras datas
- [ ] Permitir filtrar viagens por linha

**(sem data)**
- [ ] Feedback adicional (qualidade da infraestrutura, acessibilidade, atualização da informação impressa, etc.)
- [ ] Ocupação do veículo
- [ ] Combobox: Permitir pesquisar locais (geocoder) e coordenadas
- [ ] Mais informação sobre cada linha / viagem

**Comment by ricardojorgerm** [comment]
- [ ] ? FR: Seleção de trip mantida quando se clica noutras paragens por onde passa a mesma trip
Use-case: Utilizadores a decidir o local de embarque, i.e. se apanhar o autocarro aqui chega a esta hora, e se apanhar um pouco mais à frente? sera que consigo chegar a tempo?

**Comment by joao-vasconcelos** [comment]
Ver mais dias no futuro

**Comment by joao-vasconcelos** [comment]
Paragens do percurso selecionado destacadas

**Comment by joao-vasconcelos** [comment]
Animação do veículo

**Comment by joao-vasconcelos** [comment]
Arranjar zoom automático do mapa

**Comment by joao-vasconcelos** [comment]
opção de ver apenas uma linha numa paragem, mantendo ainda assim a atual opção de ter todas tbm.

**Comment by andirsun** [comment]
@joao-vasconcelos do you maybe have information about if the new real-time data is going to be used by the current ios app ? or another map apps ?

**Comment by joao-vasconcelos** [comment]
Hey @andirsun, we do not yet have a native app. However, you can use the "Add to Home Screen" iOS feature in Safari to have the website work as if it were an app. With the new macOS Sonoma it is also possible to do the same on the desktop (Open the [beta](https://beta.carrismetropolitana.pt) website in Safari and then on the toolbar go to File > Add to Dock...) We do have plans to make the realtime data available in GTFS-RT format to be consumed by all 3rd-party apps.

**Comment by ricardojorgerm** [comment]
You don't need mac, you can use Chrome and click the Install App button on the right side of the URL bar in any operating system. This also works for Edge as a PWA.

An example for another webapp: https://www.guidingtech.com/wp-content/uploads/Install-Uninstall-Pwa-in-Chrome-2_4d470f76dc99e18ad75087b1b8410ea9.png
