### ISSUE TITLE
[LinesExplorer] Combine multiple variants in a single line

### ISSUE THREAD

**Issue by joao-vasconcelos** [carrismetropolitana/website#10]
Duplicate of #12

**Comment by ricardojorgerm** [comment]
Como ponto de partida é alterar

https://github.com/carrismetropolitana/website/blob/9181baabd9762daba20abb7972165fbc3e46ef2c/nextjs/components/FrontendLinesContentPatternPathStopTimetable/FrontendLinesContentPatternPathStopTimetable.js#L66-L67

Para incluir não apenas um selected pattern mas todos os patterns com a mesma direction de uma route.

**Comment by joao-vasconcelos** [comment]
Hello @snps-grafael! We have implemented this feature in the new version of the website. If you'd like to take a look, here is an example for line 4701: https://cmet.pt/linhas/4701
The website is still in testing phase, with a few bugs to correct. We'd like to hear your opinion!
