### ISSUE TITLE
🐛 Problema com Hover no Carousel e a sua Sobreposição do Navbar

### ISSUE THREAD

**Issue by vasconevesxd** [carrismetropolitana/website#104]
## Descrição do problema  
Na página principal, ao interagir com o **carousel** apresentado, foram identificados os seguintes problemas:

1. **Comportamento estranho no hover:** Quando o hover é ativado sobre o carousel e o utilizador faz scroll na página, o carousel apresenta um comportamento de sobreposição, posicionando-se acima do navbar e afetando a experiência visual e funcional.
2. **Sobreposição do navbar:** O hover no carousel faz com que este ignore o comportamento esperado do layout, invadindo a área do navbar e prejudicando a navegação.

---

## Passos para reproduzir:

1. Aceder à página principal.
2. Identificar o **carousel** exibido na seção destacada.
3. Realizar o hover sobre o carousel.
4. Fazer scroll pela página e observar a interação com o navbar.

---

## Ambiente:

- **Browser:** Google Chrome  
- **Resolução do ecrã:** 1920x1080  
- **Dispositivo:** Desktop  

---

## Possível solução  
Mudar o z-index de 505 e 500 definidos no carousel para 3 

---

## Captura de ecrã
![image](https://github.com/user-attachments/assets/b2b10e69-9915-4dc8-85fb-b9d78247683c)

**Comment by joao-vasconcelos** [comment]
Olá @vasconevesxd, obrigado. Está corrigido.
