### ISSUE TITLE
Safari time format

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/website#14]
https://github.com/carrismetropolitana/website/blob/4686b1056bfef56e2ad3f3a00f31acf3da8cbfa0/nextjs/components/FrontendStopsTimetableDividerLine/FrontendStopsTimetableDividerLine.js#L14

Por alguma razão o Safari insiste em mostrar isto só com um digito. Não que eu ache que tenhas cometido um erro, só que é estúpido da parte desse browser.

Mas tenho uma solução para ti:  gera a hora normalmente no formato HH:mm, e depois, divide os componentes pelos dois pontos, assim. 

```js
  const now = new Date().toLocaleString('pt-PT', {
    timeZone: 'Europe/Lisbon',
    hour: '2-digit',
    minute: '2-digit'
  });

  const [hours, minutes] = now.split(':');
```
Assim já podes usar 

```html
{hours}<span>:</span>{minutes}
```

à vontade.

**Comment by joao-vasconcelos** [comment]
Muito obrigado @ricardojorgerm
