### ISSUE TITLE
Possible logical error

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/website#17]
At:

https://github.com/carrismetropolitana/website/blob/ac7b4a9ffd114a117c35267f1f729c14f7889d5e/nextjs/app/%5Blocale%5D/(frontend)/lines/%5Bline_id%5D/page.js#L16

Looks like the condition is true if

- the line is 'all' (i.e. not selected)
- the line short name is falsy (should there not be a question mark on lineData?)
- the double negative implies the line long name is truthy (is this intended?)

Should the line be

```js

	if (params.line_id === 'all' || !lineData?.short_name || !lineData?.long_name) {
```

Sorry if i misinterpreted

**Comment by joao-vasconcelos** [comment]
Olá @ricardojorgerm, vou fechar e dar como concluído pois acredito estar corrigido na versão "beta" do site. Na versão "alpha" está a ser utilizado outro método para gerir os URLs. Obrigado!
