### ISSUE TITLE
Mudanças primeiro de novembro ainda não atualizadas e corrupção de PDF

### ISSUE THREAD

**Issue by LaPingvino** [carrismetropolitana/website#3]
As melhoras para a linha 4701 ainda não aparecem no site e o PDF aí (mas parece-me que também com ao menos uma parte do resto) duplica os dias úteis do tempo escolar nos domingos/feriados erradamente. Duvido onde pôr isto e imagino que seja resolvido em tempo, mas já que chegamos muito perto à data da introdução destas mudanças, parecia-me apto indicar aqui...

**Comment by joao-vasconcelos** [comment]
Olá @LaPingvino, a oferta de Novembro já foi atualizada no site. Deverá ficar disponível nas próximas horas.

Neste momento a atualização antecipada do GTFS não funciona como gostaríamos. Estamos a desenvolver um novo sistema que nos permite ser mais ágeis neste ponto:
- Ferramenta "merger" que combina vários feeds individuais num só, através da leitura das datas de validade de cada ficheiro feed_info.txt. Existem algumas complexidades neste ponto relativamente à exclusão de calendários, trips, rotas, fares, etc. das linhas que operam fora da data de validade de cada GTFS;
- Ferramenta "website" (beta) que substituirá a atual visualização de horários, incorporando a possibilidade de vários patterns terem datas de vigência.

As alterações de oferta acompanham sempre avisos (no site e outras apps), notícias, posts nas várias redes sociais e comunicações diretas com as câmaras municipais e juntas de freguesia.

Não consigo neste momento dar uma estimativa de quando teremos estas ferramentas operacionais.

Toda a ajuda é bem vinda!

Obrigado!
