### ISSUE TITLE
Consulta de horários com possibilidade de ver todas as variantes juntas 

### ISSUE THREAD

**Issue by ScriptForAll** [carrismetropolitana/website#7]
Venho propor a implementação de uma opção de se ver o horário de uma dada linha que inclua também os horários de todas as variantes.

Atualmente só se consegue ter este tipo de visualização através dos horários em formato em pdf. 
No entanto, esta via tem os seus problemas uma vez que os pdfs ou não estão disponíveis ou não estão atualizados.

Este tipo de visualização é particularmente útil para linhas que tenham várias alíneas pois permite uma leitura mais fácil das frequências que uma dada linha tem.

**Comment by joao-vasconcelos** [comment]
Olá @ScriptForAll, obrigado pela sugestão e lamento a demora na resposta. Esta funcionalidade está implementada no novo site, em versão "alpha". Exemplo para a linha 4701: https://cmet.pt/linhas/4701

O website ainda está em fase de testes com vários bugs para corrigir. Gostávamos de receber feedback sobre este tema! 😄

**Comment by joao-vasconcelos** [comment]
Duplicate of #12
