### ISSUE TITLE
Use search parameters as in the widget

### ISSUE THREAD

**Issue by ricardojorgerm** [carrismetropolitana/website#88]
https://github.com/carrismetropolitana/website/blob/5c1d9b6f366f94d41d4dd5799e75fcfbaa75ec8d/frontend/contexts/StopsList.context.tsx#L124-L129

should actually be corrected to match criteria

https://github.com/carrismetropolitana/website/blob/5c1d9b6f366f94d41d4dd5799e75fcfbaa75ec8d/frontend/components/common/SelectStop/index.tsx#L61-L67

otherwise main stop search does not support tts disambiguation as intended

**Comment by ricardojorgerm** [comment]
also, on the opposite side, the widget has the right search params but is disabled to boost favorites, was that intended?

**Comment by joao-vasconcelos** [comment]
Done! Thank you : )
