### ISSUE TITLE
🐛 Transição das Tabs com problemas e sobreposição das Tabs 

### ISSUE THREAD

**Issue by vasconevesxd** [carrismetropolitana/website#98]
## Descrição do problema
Ao fazer scroll na página específica das paragens, como por exemplo: https://www.carrismetropolitana.pt/stops/010049, foram identificados os seguintes problemas:

1. **Transição com problemas:** Durante o scroll, a transição da tabs(Hoje ,Amanhã, Data) para o texto "Horários estimados de passagem na paragem..." apresenta comportamentos estranhos em determinados pontos, o que torna a experiência visual inconsistente.
2. **Sobreposição das Tabs superior direito:** As mesmas tabs anteriormente mencionado na parte superior direita ao pé do mapa, exibe um comportamento incorreto — em vez de uma borda arredondada, surge uma ponta bicuda devido a uma sobreposição do elemento.

## Passos para reproduzir:
1. Aceder à página de exemplo: https://www.carrismetropolitana.pt/stops/010049.
2. Fazer scroll para baixo lentamente, observando a transição das tabs.
3. Verificar as tabs no canto superior direito enquanto o conteúdo é carregado e ajustado ao scroll.

## Ambiente
Browser: Google Chrome
Resolução do ecrã: 1920x1080
Dispositivo: Desktop

## Possível solução

- Relativamente a ponta bicuda a implementação deste css nas tabs resolve em certa forma o problema `border-radius: var(--border-radius-lg)`

## Captura de ecrã

![image](https://github.com/user-attachments/assets/d7119fea-2bb6-4aff-b728-d7f855cf210d)

**Comment by joao-vasconcelos** [comment]
Olá @vasconevesxd, muito obrigado! Resolvido o border-radius. O outro é mais complexo pois depende da altura do elemento sticky. Se a altura for menor que o seletor de datas, então entra numa espécie de loop infinito até o utilizador fazer mais scroll. Idealmente encontra-se uma informação mais útil para colocar ali para forçar um bocadinho a altura.
